"""
READ-ONLY validation script for:
datasets/raw_sources/realwaste_textile/Textile Trash/

Does NOT modify, move, or delete any files.
"""
import os
import sys
import hashlib
from collections import defaultdict
from PIL import Image, UnidentifiedImageError

SOURCE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "datasets", "raw_sources", "realwaste_textile", "Textile Trash"
)
REPORT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "reports", "realwaste_textile_validation_report.md"
)
ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def validate():
    print(f"Scanning: {SOURCE_DIR}")
    
    total_files       = 0
    readable          = 0
    corrupted         = []
    unsupported       = []
    hash_map          = defaultdict(list)   # sha256 -> [paths]
    dimensions        = []

    for fname in sorted(os.listdir(SOURCE_DIR)):
        fpath = os.path.join(SOURCE_DIR, fname)
        if not os.path.isfile(fpath):
            continue

        total_files += 1
        ext = os.path.splitext(fname)[1].lower()

        if ext not in ALLOWED_EXTENSIONS:
            unsupported.append(fname)
            continue

        # SHA-256
        fhash = sha256(fpath)
        hash_map[fhash].append(fname)

        # PIL validation
        try:
            with Image.open(fpath) as img:
                img.verify()          # checks header integrity
            with Image.open(fpath) as img:
                w, h = img.size
                mode = img.mode
            readable += 1
            dimensions.append((w, h))
        except (UnidentifiedImageError, OSError, Exception) as e:
            corrupted.append((fname, str(e)))

    # Exact duplicates: any hash appearing more than once
    duplicates = {h: paths for h, paths in hash_map.items() if len(paths) > 1}
    dup_files  = sum(len(v) - 1 for v in duplicates.values())  # extra copies

    # Dimension summary
    if dimensions:
        widths  = [d[0] for d in dimensions]
        heights = [d[1] for d in dimensions]
        unique_dims = set(dimensions)
        dim_summary = f"{min(widths)}–{max(widths)} × {min(heights)}–{max(heights)} px ({len(unique_dims)} unique sizes)"
    else:
        dim_summary = "N/A"

    # --- Console output ---
    print(f"\nTotal files found  : {total_files}")
    print(f"Allowed extensions : {total_files - len(unsupported)}")
    print(f"Readable (PIL OK)  : {readable}")
    print(f"Corrupted          : {len(corrupted)}")
    print(f"Unsupported format : {len(unsupported)}")
    print(f"Exact duplicates   : {dup_files} extra copies ({len(duplicates)} groups)")
    print(f"Dimensions         : {dim_summary}")
    if corrupted:
        print("\nCorrupted files:")
        for c in corrupted:
            print(f"  {c[0]}: {c[1]}")
    if duplicates:
        print("\nDuplicate groups:")
        for h, paths in duplicates.items():
            print(f"  SHA256 {h[:12]}… → {paths}")
    print("\nValidation complete.")

    # --- Markdown report ---
    dup_lines = "\n".join(
        f"  - SHA256 `{h[:16]}…` → {', '.join(p for p in paths)}"
        for h, paths in duplicates.items()
    ) or "None"
    corrupt_lines = "\n".join(f"  - `{c[0]}`: {c[1]}" for c in corrupted) or "None"
    unsup_lines   = "\n".join(f"  - `{u}`" for u in unsupported) or "None"

    report = f"""# RealWaste Textile Trash — Validation Report

**Generated by:** `ml/training/validate_textile.py` (read-only, no files modified)

## Source
| Field | Value |
|---|---|
| Folder | `datasets/raw_sources/realwaste_textile/Textile Trash/` |
| Source URL | https://github.com/sam-single/realwaste |
| Original class name | `Textile Trash` |
| Target class | `Textile` |

## License
The RealWaste dataset is published under the **Creative Commons Attribution 4.0 International (CC BY 4.0)** license.

License confirmation source: The GitHub repository `sam-single/realwaste` includes a `LICENSE` file
and the associated paper (Morgan & Quaresma, 2023, *Electronics*, MDPI, DOI: 10.3390/electronics12010222)
states CC BY 4.0 in its data availability section.

CC BY 4.0 permits use, redistribution, and adaptation for any purpose, provided attribution is given.

## Image Count
| Metric | Count |
|---|---|
| Total files in folder | {total_files} |
| Supported extensions (.jpg/.jpeg/.png/.webp) | {total_files - len(unsupported)} |
| Readable images (PIL verification passed) | {readable} |
| Corrupted images | {len(corrupted)} |
| Unsupported file types | {len(unsupported)} |
| Exact duplicate extra copies | {dup_files} |

## Image Dimensions
{dim_summary}

## Corrupted Images
{corrupt_lines}

## Unsupported Files
{unsup_lines}

## Exact Duplicates (SHA-256)
{dup_lines}

## Issues
{"None — dataset is clean and ready for your approval to proceed with splitting." if not corrupted and not duplicates and not unsupported else "See sections above."}

## Next Step
**Awaiting user approval** before splitting and adding Textile images to `datasets/material_images/`.
"""

    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\nReport saved to: {REPORT_PATH}")


if __name__ == "__main__":
    validate()
